-- Oracle Relational Schema for Employee Benchmark
-- Run with SQL*Plus or SQLcl after creating the user/schema.
-- Adjust tablespace/storage as needed.

-- Drop objects if they exist
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE DEPARTMENTS CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- Base tables
CREATE TABLE DEPARTMENTS (
  DEPT_ID NUMBER PRIMARY KEY,
  DEPT_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE EMPLOYEES (
  EMP_ID NUMBER PRIMARY KEY,
  FIRST_NAME VARCHAR2(50) NOT NULL,
  LAST_NAME VARCHAR2(50) NOT NULL,
  DEPT_ID NUMBER NOT NULL,
  SALARY NUMBER NOT NULL CHECK (SALARY >= 0),
  HIRE_DATE DATE NOT NULL,
  EMAIL VARCHAR2(120) UNIQUE,
  CONSTRAINT EMP_DEPT_FK FOREIGN KEY (DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID)
);

-- Seed departments
INSERT ALL
  INTO DEPARTMENTS(DEPT_ID, DEPT_NAME) VALUES (10,'HR')
  INTO DEPARTMENTS(DEPT_ID, DEPT_NAME) VALUES (20,'Finance')
  INTO DEPARTMENTS(DEPT_ID, DEPT_NAME) VALUES (30,'Engineering')
  INTO DEPARTMENTS(DEPT_ID, DEPT_NAME) VALUES (40,'Sales')
  INTO DEPARTMENTS(DEPT_ID, DEPT_NAME) VALUES (50,'Support')
  INTO DEPARTMENTS(DEPT_ID, DEPT_NAME) VALUES (60,'R&D')
  INTO DEPARTMENTS(DEPT_ID, DEPT_NAME) VALUES (70,'Logistics')
  INTO DEPARTMENTS(DEPT_ID, DEPT_NAME) VALUES (80,'Marketing')
SELECT 1 FROM DUAL;

COMMIT;

-- Helpful indexes
CREATE INDEX EMP_DEPT_IDX ON EMPLOYEES(DEPT_ID);
CREATE INDEX EMP_HIREDATE_IDX ON EMPLOYEES(HIRE_DATE);
